/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID ubuntu)
#  Generated on:      Wed Apr 11 14:15:13 2018
#  Design:            divider
#  Command:           saveNetlist results/divider.routed.v
###############################################################
*/
module divider_DW01_sub_1 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [32:0] A;
   input [32:0] B;
   input CI;
   output [32:0] DIFF;
   output CO;

   // Internal wires
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n37;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n45;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n53;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n61;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n69;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n81;
   wire n83;
   wire n84;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n156;
   wire n158;
   wire n160;
   wire n162;
   wire n164;
   wire n166;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;

   FA_X1 U2 (.S(DIFF[31]),
	.CO(n26),
	.CI(n27),
	.B(A[31]),
	.A(n179));
   FA_X1 U4 (.S(DIFF[29]),
	.CO(n28),
	.CI(n29),
	.B(A[29]),
	.A(n181));
   FA_X1 U5 (.S(DIFF[28]),
	.CO(n29),
	.CI(n30),
	.B(A[28]),
	.A(n182));
   FA_X1 U6 (.S(DIFF[27]),
	.CO(n30),
	.CI(n31),
	.B(A[27]),
	.A(n183));
   FA_X1 U7 (.S(DIFF[26]),
	.CO(n31),
	.CI(n32),
	.B(A[26]),
	.A(n184));
   NOR2_X1 U241 (.ZN(n89),
	.A2(A[13]),
	.A1(n197));
   NOR2_X1 U242 (.ZN(n147),
	.A2(A[2]),
	.A1(n208));
   NOR2_X1 U243 (.ZN(n133),
	.A2(A[5]),
	.A1(n205));
   NOR2_X1 U244 (.ZN(n125),
	.A2(A[7]),
	.A1(n203));
   NOR2_X1 U245 (.ZN(n128),
	.A2(A[6]),
	.A1(n204));
   NOR2_X1 U246 (.ZN(n153),
	.A2(A[0]),
	.A1(n210));
   AOI21_X1 U247 (.ZN(n43),
	.B2(n322),
	.B1(n48),
	.A(n45));
   AOI21_X1 U248 (.ZN(n51),
	.B2(n323),
	.B1(n56),
	.A(n53));
   AOI21_X1 U249 (.ZN(n99),
	.B2(n113),
	.B1(n100),
	.A(n101));
   NOR2_X1 U253 (.ZN(n102),
	.A2(A[11]),
	.A1(n199));
   NAND2_X1 U256 (.ZN(n95),
	.A2(A[12]),
	.A1(n198));
   NAND2_X1 U257 (.ZN(n148),
	.A2(A[2]),
	.A1(n208));
   INV_X1 U259 (.ZN(n96),
	.A(n97));
   NAND2_X1 U260 (.ZN(n98),
	.A2(n100),
	.A1(n112));
   INV_X1 U261 (.ZN(n119),
	.A(n120));
   AOI21_X1 U262 (.ZN(n130),
	.B2(n131),
	.B1(n140),
	.A(n132));
   OAI21_X1 U263 (.ZN(n109),
	.B2(n110),
	.B1(n119),
	.A(n111));
   INV_X1 U264 (.ZN(n110),
	.A(n112));
   OAI21_X1 U265 (.ZN(n97),
	.B2(n98),
	.B1(n119),
	.A(n99));
   INV_X1 U266 (.ZN(n140),
	.A(n141));
   INV_X1 U270 (.ZN(n149),
	.A(n150));
   OAI21_X1 U271 (.ZN(n64),
	.B2(n65),
	.B1(n67),
	.A(n66));
   OAI21_X1 U272 (.ZN(n56),
	.B2(n57),
	.B1(n59),
	.A(n58));
   OAI21_X1 U273 (.ZN(n72),
	.B2(n73),
	.B1(n75),
	.A(n74));
   OAI21_X1 U274 (.ZN(n48),
	.B2(n49),
	.B1(n51),
	.A(n50));
   OAI21_X1 U275 (.ZN(n113),
	.B2(n118),
	.B1(n114),
	.A(n115));
   OAI21_X1 U276 (.ZN(n101),
	.B2(n108),
	.B1(n102),
	.A(n103));
   OAI21_X1 U277 (.ZN(n132),
	.B2(n139),
	.B1(n133),
	.A(n134));
   OAI21_X1 U278 (.ZN(n40),
	.B2(n41),
	.B1(n43),
	.A(n42));
   INV_X1 U279 (.ZN(n37),
	.A(n39));
   INV_X1 U280 (.ZN(n53),
	.A(n55));
   INV_X1 U281 (.ZN(n45),
	.A(n47));
   NOR2_X1 U282 (.ZN(n131),
	.A2(n133),
	.A1(n138));
   OAI21_X1 U283 (.ZN(n150),
	.B2(n153),
	.B1(n151),
	.A(n152));
   NOR2_X1 U284 (.ZN(n100),
	.A2(n102),
	.A1(n107));
   OAI21_X1 U285 (.ZN(n88),
	.B2(n95),
	.B1(n89),
	.A(n90));
   OAI21_X1 U286 (.ZN(n120),
	.B2(n121),
	.B1(n141),
	.A(n122));
   NAND2_X1 U287 (.ZN(n121),
	.A2(n123),
	.A1(n131));
   AOI21_X1 U288 (.ZN(n122),
	.B2(n132),
	.B1(n123),
	.A(n124));
   NOR2_X1 U289 (.ZN(n123),
	.A2(n125),
	.A1(n128));
   AOI21_X1 U290 (.ZN(n79),
	.B2(n319),
	.B1(n88),
	.A(n81));
   INV_X1 U291 (.ZN(n81),
	.A(n83));
   NOR2_X1 U292 (.ZN(n76),
	.A2(n78),
	.A1(n98));
   OAI21_X1 U293 (.ZN(n77),
	.B2(n78),
	.B1(n99),
	.A(n79));
   NAND2_X1 U294 (.ZN(n78),
	.A2(n319),
	.A1(n87));
   AOI21_X1 U295 (.ZN(n67),
	.B2(n321),
	.B1(n72),
	.A(n69));
   INV_X1 U296 (.ZN(n69),
	.A(n71));
   INV_X1 U297 (.ZN(n61),
	.A(n63));
   NOR2_X1 U298 (.ZN(n87),
	.A2(n89),
	.A1(n94));
   NOR2_X1 U299 (.ZN(n112),
	.A2(n114),
	.A1(n117));
   AOI21_X1 U300 (.ZN(n141),
	.B2(n150),
	.B1(n142),
	.A(n143));
   NOR2_X1 U301 (.ZN(n142),
	.A2(n144),
	.A1(n147));
   OAI21_X1 U302 (.ZN(n143),
	.B2(n148),
	.B1(n144),
	.A(n145));
   OAI21_X1 U303 (.ZN(n124),
	.B2(n129),
	.B1(n125),
	.A(n126));
   AOI21_X1 U304 (.ZN(n91),
	.B2(n92),
	.B1(n97),
	.A(n93));
   INV_X1 U305 (.ZN(n93),
	.A(n95));
   AOI21_X1 U306 (.ZN(n104),
	.B2(n169),
	.B1(n109),
	.A(n106));
   INV_X1 U307 (.ZN(n106),
	.A(n108));
   AOI21_X1 U308 (.ZN(n135),
	.B2(n175),
	.B1(n140),
	.A(n137));
   INV_X1 U309 (.ZN(n137),
	.A(n139));
   INV_X1 U310 (.ZN(n92),
	.A(n94));
   INV_X1 U311 (.ZN(n169),
	.A(n107));
   INV_X1 U312 (.ZN(n175),
	.A(n138));
   OAI21_X1 U313 (.ZN(n116),
	.B2(n117),
	.B1(n119),
	.A(n118));
   OAI21_X1 U314 (.ZN(n127),
	.B2(n128),
	.B1(n130),
	.A(n129));
   OAI21_X1 U315 (.ZN(n146),
	.B2(n147),
	.B1(n149),
	.A(n148));
   INV_X1 U316 (.ZN(n171),
	.A(n117));
   INV_X1 U317 (.ZN(n173),
	.A(n128));
   INV_X1 U318 (.ZN(n177),
	.A(n147));
   INV_X1 U319 (.ZN(n166),
	.A(n89));
   INV_X1 U320 (.ZN(n172),
	.A(n125));
   INV_X1 U321 (.ZN(n174),
	.A(n133));
   INV_X1 U322 (.ZN(n176),
	.A(n144));
   INV_X1 U323 (.ZN(n170),
	.A(n114));
   INV_X1 U324 (.ZN(n178),
	.A(n151));
   INV_X1 U325 (.ZN(n156),
	.A(n41));
   INV_X1 U326 (.ZN(n158),
	.A(n49));
   INV_X1 U327 (.ZN(n160),
	.A(n57));
   INV_X1 U328 (.ZN(n162),
	.A(n65));
   INV_X1 U329 (.ZN(n164),
	.A(n73));
   INV_X1 U330 (.ZN(n154),
	.A(n33));
   INV_X1 U331 (.ZN(n168),
	.A(n102));
   NOR2_X1 U332 (.ZN(n117),
	.A2(A[8]),
	.A1(n202));
   NOR2_X1 U333 (.ZN(n144),
	.A2(A[3]),
	.A1(n207));
   XOR2_X1 U334 (.Z(DIFF[5]),
	.B(n21),
	.A(n135));
   NAND2_X1 U335 (.ZN(n21),
	.A2(n134),
	.A1(n174));
   XNOR2_X1 U336 (.ZN(DIFF[4]),
	.B(n22),
	.A(n140));
   NAND2_X1 U337 (.ZN(n22),
	.A2(n139),
	.A1(n175));
   XNOR2_X1 U338 (.ZN(DIFF[3]),
	.B(n23),
	.A(n146));
   NAND2_X1 U339 (.ZN(n23),
	.A2(n145),
	.A1(n176));
   XOR2_X1 U340 (.Z(DIFF[2]),
	.B(n24),
	.A(n149));
   NAND2_X1 U341 (.ZN(n24),
	.A2(n148),
	.A1(n177));
   XOR2_X1 U342 (.Z(DIFF[1]),
	.B(n153),
	.A(n25));
   NAND2_X1 U343 (.ZN(n25),
	.A2(n152),
	.A1(n178));
   NOR2_X1 U344 (.ZN(n114),
	.A2(A[9]),
	.A1(n201));
   OR2_X1 U345 (.ZN(n319),
	.A2(A[14]),
	.A1(n196));
   NOR2_X1 U346 (.ZN(n107),
	.A2(A[10]),
	.A1(n200));
   NOR2_X1 U347 (.ZN(n94),
	.A2(A[12]),
	.A1(n198));
   NOR2_X1 U348 (.ZN(n138),
	.A2(A[4]),
	.A1(n206));
   NOR2_X1 U349 (.ZN(n151),
	.A2(A[1]),
	.A1(n209));
   INV_X1 U350 (.ZN(n181),
	.A(B[29]));
   NAND2_X1 U351 (.ZN(n1),
	.A2(n34),
	.A1(n154));
   NAND2_X1 U352 (.ZN(n2),
	.A2(n39),
	.A1(n324));
   XOR2_X1 U353 (.Z(DIFF[23]),
	.B(n3),
	.A(n43));
   NAND2_X1 U354 (.ZN(n3),
	.A2(n42),
	.A1(n156));
   NAND2_X1 U355 (.ZN(n4),
	.A2(n47),
	.A1(n322));
   XOR2_X1 U356 (.Z(DIFF[21]),
	.B(n5),
	.A(n51));
   NAND2_X1 U357 (.ZN(n5),
	.A2(n50),
	.A1(n158));
   XNOR2_X1 U358 (.ZN(DIFF[20]),
	.B(n6),
	.A(n56));
   NAND2_X1 U359 (.ZN(n6),
	.A2(n55),
	.A1(n323));
   NAND2_X1 U360 (.ZN(n7),
	.A2(n58),
	.A1(n160));
   XNOR2_X1 U361 (.ZN(DIFF[18]),
	.B(n8),
	.A(n64));
   NAND2_X1 U362 (.ZN(n8),
	.A2(n63),
	.A1(n320));
   NAND2_X1 U363 (.ZN(n9),
	.A2(n66),
	.A1(n162));
   NAND2_X1 U364 (.ZN(n10),
	.A2(n71),
	.A1(n321));
   NAND2_X1 U365 (.ZN(n11),
	.A2(n74),
	.A1(n164));
   XNOR2_X1 U366 (.ZN(DIFF[14]),
	.B(n12),
	.A(n84));
   NAND2_X1 U367 (.ZN(n12),
	.A2(n83),
	.A1(n319));
   XOR2_X1 U368 (.Z(DIFF[13]),
	.B(n13),
	.A(n91));
   NAND2_X1 U369 (.ZN(n13),
	.A2(n90),
	.A1(n166));
   XOR2_X1 U370 (.Z(DIFF[12]),
	.B(n14),
	.A(n96));
   NAND2_X1 U371 (.ZN(n14),
	.A2(n95),
	.A1(n92));
   XOR2_X1 U372 (.Z(DIFF[11]),
	.B(n15),
	.A(n104));
   NAND2_X1 U373 (.ZN(n15),
	.A2(n103),
	.A1(n168));
   XNOR2_X1 U374 (.ZN(DIFF[10]),
	.B(n16),
	.A(n109));
   NAND2_X1 U375 (.ZN(n16),
	.A2(n108),
	.A1(n169));
   XNOR2_X1 U376 (.ZN(DIFF[9]),
	.B(n17),
	.A(n116));
   NAND2_X1 U377 (.ZN(n17),
	.A2(n115),
	.A1(n170));
   XOR2_X1 U378 (.Z(DIFF[8]),
	.B(n18),
	.A(n119));
   NAND2_X1 U379 (.ZN(n18),
	.A2(n118),
	.A1(n171));
   XNOR2_X1 U380 (.ZN(DIFF[7]),
	.B(n19),
	.A(n127));
   NAND2_X1 U381 (.ZN(n19),
	.A2(n126),
	.A1(n172));
   XOR2_X1 U382 (.Z(DIFF[6]),
	.B(n20),
	.A(n130));
   NAND2_X1 U383 (.ZN(n20),
	.A2(n129),
	.A1(n173));
   XNOR2_X1 U384 (.ZN(DIFF[0]),
	.B(A[0]),
	.A(n210));
   INV_X1 U385 (.ZN(n197),
	.A(B[13]));
   INV_X1 U386 (.ZN(n198),
	.A(B[12]));
   INV_X1 U387 (.ZN(n204),
	.A(B[6]));
   INV_X1 U388 (.ZN(n200),
	.A(B[10]));
   INV_X1 U389 (.ZN(n208),
	.A(B[2]));
   INV_X1 U390 (.ZN(n202),
	.A(B[8]));
   INV_X1 U391 (.ZN(n205),
	.A(B[5]));
   INV_X1 U392 (.ZN(n203),
	.A(B[7]));
   INV_X1 U393 (.ZN(n209),
	.A(B[1]));
   INV_X1 U394 (.ZN(n201),
	.A(B[9]));
   INV_X1 U395 (.ZN(n207),
	.A(B[3]));
   INV_X1 U396 (.ZN(n206),
	.A(B[4]));
   INV_X1 U397 (.ZN(n192),
	.A(B[18]));
   INV_X1 U398 (.ZN(n193),
	.A(B[17]));
   INV_X1 U399 (.ZN(n194),
	.A(B[16]));
   INV_X1 U400 (.ZN(n195),
	.A(B[15]));
   INV_X1 U401 (.ZN(n196),
	.A(B[14]));
   NOR2_X1 U402 (.ZN(n65),
	.A2(A[17]),
	.A1(n193));
   NOR2_X1 U403 (.ZN(n73),
	.A2(A[15]),
	.A1(n195));
   NAND2_X1 U404 (.ZN(n129),
	.A2(A[6]),
	.A1(n204));
   INV_X1 U405 (.ZN(n210),
	.A(B[0]));
   NAND2_X1 U406 (.ZN(n139),
	.A2(A[4]),
	.A1(n206));
   NAND2_X1 U407 (.ZN(n118),
	.A2(A[8]),
	.A1(n202));
   INV_X1 U408 (.ZN(n184),
	.A(B[26]));
   INV_X1 U409 (.ZN(n183),
	.A(B[27]));
   INV_X1 U410 (.ZN(n182),
	.A(B[28]));
   NAND2_X1 U411 (.ZN(n108),
	.A2(A[10]),
	.A1(n200));
   INV_X1 U412 (.ZN(n179),
	.A(B[31]));
   NAND2_X1 U413 (.ZN(n145),
	.A2(A[3]),
	.A1(n207));
   NAND2_X1 U414 (.ZN(n90),
	.A2(A[13]),
	.A1(n197));
   NAND2_X1 U415 (.ZN(n126),
	.A2(A[7]),
	.A1(n203));
   NAND2_X1 U416 (.ZN(n134),
	.A2(A[5]),
	.A1(n205));
   NAND2_X1 U417 (.ZN(n152),
	.A2(A[1]),
	.A1(n209));
   OR2_X1 U418 (.ZN(n320),
	.A2(A[18]),
	.A1(n192));
   OR2_X1 U419 (.ZN(n321),
	.A2(A[16]),
	.A1(n194));
   NAND2_X1 U420 (.ZN(n63),
	.A2(A[18]),
	.A1(n192));
   NAND2_X1 U421 (.ZN(n71),
	.A2(A[16]),
	.A1(n194));
   NAND2_X1 U422 (.ZN(n83),
	.A2(A[14]),
	.A1(n196));
   NAND2_X1 U423 (.ZN(n115),
	.A2(A[9]),
	.A1(n201));
   NAND2_X1 U424 (.ZN(n66),
	.A2(A[17]),
	.A1(n193));
   NAND2_X1 U425 (.ZN(n74),
	.A2(A[15]),
	.A1(n195));
   INV_X1 U426 (.ZN(n185),
	.A(B[25]));
   INV_X1 U427 (.ZN(n186),
	.A(B[24]));
   INV_X1 U428 (.ZN(n187),
	.A(B[23]));
   INV_X1 U429 (.ZN(n188),
	.A(B[22]));
   INV_X1 U430 (.ZN(n189),
	.A(B[21]));
   INV_X1 U431 (.ZN(n190),
	.A(B[20]));
   INV_X1 U432 (.ZN(n191),
	.A(B[19]));
   OR2_X1 U433 (.ZN(n322),
	.A2(A[22]),
	.A1(n188));
   OR2_X1 U434 (.ZN(n323),
	.A2(A[20]),
	.A1(n190));
   NOR2_X1 U435 (.ZN(n41),
	.A2(A[23]),
	.A1(n187));
   NOR2_X1 U436 (.ZN(n49),
	.A2(A[21]),
	.A1(n189));
   NOR2_X1 U437 (.ZN(n57),
	.A2(A[19]),
	.A1(n191));
   NOR2_X1 U438 (.ZN(n33),
	.A2(A[25]),
	.A1(n185));
   OR2_X1 U439 (.ZN(n324),
	.A2(A[24]),
	.A1(n186));
   NAND2_X1 U440 (.ZN(n39),
	.A2(A[24]),
	.A1(n186));
   NAND2_X1 U441 (.ZN(n47),
	.A2(A[22]),
	.A1(n188));
   NAND2_X1 U442 (.ZN(n55),
	.A2(A[20]),
	.A1(n190));
   NAND2_X1 U443 (.ZN(n42),
	.A2(A[23]),
	.A1(n187));
   NAND2_X1 U444 (.ZN(n50),
	.A2(A[21]),
	.A1(n189));
   NAND2_X1 U445 (.ZN(n58),
	.A2(A[19]),
	.A1(n191));
   NAND2_X1 U446 (.ZN(n34),
	.A2(A[25]),
	.A1(n185));
   XOR2_X1 U447 (.Z(n325),
	.B(A[30]),
	.A(n180));
   XOR2_X1 U448 (.Z(DIFF[30]),
	.B(n325),
	.A(n28));
   NAND2_X1 U449 (.ZN(n326),
	.A2(n180),
	.A1(n28));
   NAND2_X1 U450 (.ZN(n327),
	.A2(A[30]),
	.A1(n28));
   NAND2_X1 U451 (.ZN(n328),
	.A2(A[30]),
	.A1(n180));
   NAND3_X1 U452 (.ZN(n27),
	.A3(n327),
	.A2(n328),
	.A1(n326));
   INV_X1 U453 (.ZN(n180),
	.A(B[30]));
   XNOR2_X1 U454 (.ZN(DIFF[24]),
	.B(n2),
	.A(n40));
   XNOR2_X1 U455 (.ZN(DIFF[16]),
	.B(n10),
	.A(n72));
   XOR2_X1 U456 (.Z(DIFF[19]),
	.B(n7),
	.A(n59));
   XOR2_X1 U457 (.Z(DIFF[17]),
	.B(n9),
	.A(n67));
   XOR2_X1 U458 (.Z(DIFF[15]),
	.B(n11),
	.A(n75));
   INV_X1 U459 (.ZN(n111),
	.A(n113));
   NAND2_X1 U460 (.ZN(n103),
	.A2(A[11]),
	.A1(n199));
   INV_X1 U461 (.ZN(DIFF[32]),
	.A(n26));
   XNOR2_X1 U462 (.ZN(DIFF[22]),
	.B(n4),
	.A(n48));
   XOR2_X1 U463 (.Z(DIFF[25]),
	.B(n1),
	.A(n35));
   OAI21_X1 U464 (.ZN(n32),
	.B2(n33),
	.B1(n35),
	.A(n34));
   INV_X1 U465 (.ZN(n199),
	.A(B[11]));
   AOI21_X1 U251 (.ZN(n35),
	.B2(n324),
	.B1(n40),
	.A(n37));
   AOI21_X1 U252 (.ZN(n59),
	.B2(n320),
	.B1(n64),
	.A(n61));
   AOI21_X1 U250 (.ZN(n75),
	.B2(n76),
	.B1(n120),
	.A(n77));
   INV_X1 U254 (.ZN(n84),
	.A(n329));
   AOI21_X1 U255 (.ZN(n329),
	.B2(n87),
	.B1(n97),
	.A(n88));
endmodule

module divider (
	clk, 
	rst, 
	start, 
	dividend, 
	divisor, 
	done, 
	quotient, 
	remainder);
   input clk;
   input rst;
   input start;
   input [31:0] dividend;
   input [31:0] divisor;
   output done;
   output [31:0] quotient;
   output [31:0] remainder;

   // Internal wires
   wire clk__L2_N5;
   wire clk__L2_N4;
   wire clk__L2_N3;
   wire clk__L2_N2;
   wire clk__L2_N1;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire FE_OFN1_n352;
   wire FE_OFN0_n147;
   wire state_reg_1_;
   wire N230;
   wire N231;
   wire N232;
   wire N233;
   wire N234;
   wire n3;
   wire n4;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n75;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n147;
   wire n178;
   wire n180;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n218;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire n445;
   wire n446;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n458;
   wire n459;
   wire n460;
   wire n461;
   wire n462;
   wire n463;
   wire n464;
   wire n465;
   wire n466;
   wire n467;
   wire n468;
   wire n469;
   wire n470;
   wire [31:0] divisor_reg;
   wire [63:0] remainder_reg;
   wire [5:0] cnt_reg;
   wire [32:0] alu_result;
   wire [5:2] add_117_carry;

   CLKBUF_X3 clk__L2_I5 (.Z(clk__L2_N5),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I4 (.Z(clk__L2_N4),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I3 (.Z(clk__L2_N3),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I2 (.Z(clk__L2_N2),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I1 (.Z(clk__L2_N1),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L2_I0 (.Z(clk__L2_N0),
	.A(clk__L1_N0));
   CLKBUF_X3 clk__L1_I0 (.Z(clk__L1_N0),
	.A(clk));
   CLKBUF_X2 FE_OFC1_n352 (.Z(FE_OFN1_n352),
	.A(n352));
   CLKBUF_X3 FE_OFC0_n147 (.Z(FE_OFN0_n147),
	.A(n147));
   DFF_X1 cnt_reg_reg_1_ (.Q(cnt_reg[1]),
	.D(n431),
	.CK(clk__L2_N1));
   DFF_X1 cnt_reg_reg_2_ (.Q(cnt_reg[2]),
	.D(n432),
	.CK(clk__L2_N1));
   DFF_X1 cnt_reg_reg_3_ (.Q(cnt_reg[3]),
	.D(n433),
	.CK(clk__L2_N1));
   DFF_X1 cnt_reg_reg_4_ (.Q(cnt_reg[4]),
	.D(n434),
	.CK(clk__L2_N0));
   DFF_X1 cnt_reg_reg_5_ (.Q(cnt_reg[5]),
	.D(n435),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_1_ (.QN(n67),
	.D(n309),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_2_ (.QN(n66),
	.D(n308),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_3_ (.QN(n65),
	.D(n307),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_4_ (.QN(n64),
	.D(n306),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_5_ (.QN(n63),
	.D(n305),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_6_ (.QN(n62),
	.D(n304),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_7_ (.QN(n61),
	.D(n303),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_8_ (.QN(n60),
	.D(n302),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_9_ (.QN(n59),
	.D(n301),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_10_ (.QN(n58),
	.D(n300),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_11_ (.QN(n57),
	.D(n299),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_12_ (.QN(n56),
	.D(n298),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_13_ (.QN(n55),
	.D(n297),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_14_ (.QN(n54),
	.D(n296),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_15_ (.QN(n53),
	.D(n295),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_16_ (.QN(n52),
	.D(n294),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_17_ (.QN(n51),
	.D(n293),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_18_ (.QN(n50),
	.D(n292),
	.CK(clk__L2_N0));
   DFF_X1 remainder_reg_reg_19_ (.QN(n49),
	.D(n291),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_20_ (.QN(n48),
	.D(n290),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_21_ (.QN(n47),
	.D(n289),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_22_ (.QN(n46),
	.D(n288),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_23_ (.QN(n45),
	.D(n287),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_24_ (.QN(n44),
	.D(n286),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_25_ (.QN(n43),
	.D(n285),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_26_ (.QN(n42),
	.D(n284),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_27_ (.QN(n41),
	.D(n283),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_28_ (.QN(n40),
	.D(n282),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_29_ (.QN(n39),
	.D(n281),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_30_ (.QN(n38),
	.D(n280),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_31_ (.QN(n37),
	.Q(remainder_reg[31]),
	.D(n279),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_32_ (.Q(remainder_reg[32]),
	.D(n436),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_39_ (.QN(n29),
	.Q(remainder_reg[39]),
	.D(n272),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_40_ (.QN(n28),
	.Q(remainder_reg[40]),
	.D(n271),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_64_ (.QN(n3),
	.D(n247),
	.CK(clk__L2_N3));
   NAND3_X1 U299 (.ZN(n220),
	.A3(start),
	.A2(n385),
	.A1(n387));
   NAND3_X1 U300 (.ZN(n226),
	.A3(start),
	.A2(n349),
	.A1(n346));
   NAND4_X1 U301 (.ZN(n228),
	.A4(n229),
	.A3(cnt_reg[5]),
	.A2(n75),
	.A1(n345));
   NAND4_X1 U303 (.ZN(n241),
	.A4(n442),
	.A3(n443),
	.A2(n444),
	.A1(n445));
   NAND4_X1 U304 (.ZN(n240),
	.A4(n439),
	.A3(n467),
	.A2(n440),
	.A1(n441));
   NAND4_X1 U305 (.ZN(n239),
	.A4(n464),
	.A3(n465),
	.A2(n466),
	.A1(n438));
   NAND4_X1 U306 (.ZN(n238),
	.A4(n460),
	.A3(n461),
	.A2(n462),
	.A1(n463));
   NAND4_X1 U307 (.ZN(n245),
	.A4(n457),
	.A3(n458),
	.A2(n459),
	.A1(n469));
   NAND4_X1 U308 (.ZN(n244),
	.A4(n453),
	.A3(n454),
	.A2(n455),
	.A1(n456));
   NAND4_X1 U309 (.ZN(n243),
	.A4(n468),
	.A3(n450),
	.A2(n451),
	.A1(n452));
   NAND4_X1 U310 (.ZN(n242),
	.A4(n446),
	.A3(n447),
	.A2(n448),
	.A1(n449));
   HA_X1 add_117_U1_1_1 (.S(N230),
	.CO(add_117_carry[2]),
	.B(cnt_reg[0]),
	.A(cnt_reg[1]));
   HA_X1 add_117_U1_1_2 (.S(N231),
	.CO(add_117_carry[3]),
	.B(add_117_carry[2]),
	.A(cnt_reg[2]));
   HA_X1 add_117_U1_1_3 (.S(N232),
	.CO(add_117_carry[4]),
	.B(add_117_carry[3]),
	.A(cnt_reg[3]));
   HA_X1 add_117_U1_1_4 (.S(N233),
	.CO(add_117_carry[5]),
	.B(add_117_carry[4]),
	.A(cnt_reg[4]));
   divider_DW01_sub_1 sub_80 (.A({ 1'b0,
		remainder_reg[63],
		remainder_reg[62],
		remainder_reg[61],
		remainder_reg[60],
		remainder_reg[59],
		remainder_reg[58],
		remainder_reg[57],
		remainder_reg[56],
		remainder_reg[55],
		remainder_reg[54],
		remainder_reg[53],
		remainder_reg[52],
		remainder_reg[51],
		remainder_reg[50],
		remainder_reg[49],
		remainder_reg[48],
		remainder_reg[47],
		remainder_reg[46],
		remainder_reg[45],
		remainder_reg[44],
		remainder_reg[43],
		remainder_reg[42],
		remainder_reg[41],
		remainder_reg[40],
		remainder_reg[39],
		remainder_reg[38],
		remainder_reg[37],
		remainder_reg[36],
		remainder_reg[35],
		remainder_reg[34],
		remainder_reg[33],
		remainder_reg[32] }),
	.B({ 1'b0,
		divisor_reg }),
	.CI(1'b0),
	.DIFF(alu_result));
   DFF_X1 state_reg_reg_0_ (.QN(n387),
	.Q(done),
	.D(n344),
	.CK(clk__L2_N1));
   DFF_X1 state_reg_reg_1_ (.QN(n385),
	.Q(state_reg_1_),
	.D(n343),
	.CK(clk__L2_N1));
   DFF_X1 divisor_reg_reg_7_ (.QN(n105),
	.Q(divisor_reg[7]),
	.D(n334),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_6_ (.QN(n106),
	.Q(divisor_reg[6]),
	.D(n335),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_5_ (.QN(n107),
	.Q(divisor_reg[5]),
	.D(n336),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_4_ (.QN(n108),
	.Q(divisor_reg[4]),
	.D(n337),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_3_ (.QN(n109),
	.Q(divisor_reg[3]),
	.D(n338),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_2_ (.QN(n110),
	.Q(divisor_reg[2]),
	.D(n339),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_1_ (.QN(n111),
	.Q(divisor_reg[1]),
	.D(n340),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_0_ (.QN(n112),
	.Q(divisor_reg[0]),
	.D(n341),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_31_ (.QN(n81),
	.Q(divisor_reg[31]),
	.D(n310),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_30_ (.QN(n82),
	.Q(divisor_reg[30]),
	.D(n311),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_29_ (.QN(n83),
	.Q(divisor_reg[29]),
	.D(n312),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_28_ (.QN(n84),
	.Q(divisor_reg[28]),
	.D(n313),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_27_ (.QN(n85),
	.Q(divisor_reg[27]),
	.D(n314),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_26_ (.QN(n86),
	.Q(divisor_reg[26]),
	.D(n315),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_25_ (.QN(n87),
	.Q(divisor_reg[25]),
	.D(n316),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_24_ (.QN(n88),
	.Q(divisor_reg[24]),
	.D(n317),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_23_ (.QN(n89),
	.Q(divisor_reg[23]),
	.D(n318),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_22_ (.QN(n90),
	.Q(divisor_reg[22]),
	.D(n319),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_21_ (.QN(n91),
	.Q(divisor_reg[21]),
	.D(n320),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_20_ (.QN(n92),
	.Q(divisor_reg[20]),
	.D(n321),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_19_ (.QN(n93),
	.Q(divisor_reg[19]),
	.D(n322),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_18_ (.QN(n94),
	.Q(divisor_reg[18]),
	.D(n323),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_17_ (.QN(n95),
	.Q(divisor_reg[17]),
	.D(n324),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_16_ (.QN(n96),
	.Q(divisor_reg[16]),
	.D(n325),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_15_ (.QN(n97),
	.Q(divisor_reg[15]),
	.D(n326),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_14_ (.QN(n98),
	.Q(divisor_reg[14]),
	.D(n327),
	.CK(clk__L2_N5));
   DFF_X1 divisor_reg_reg_13_ (.QN(n99),
	.Q(divisor_reg[13]),
	.D(n328),
	.CK(clk__L2_N4));
   DFF_X1 divisor_reg_reg_12_ (.QN(n100),
	.Q(divisor_reg[12]),
	.D(n329),
	.CK(clk__L2_N1));
   DFF_X1 divisor_reg_reg_11_ (.QN(n101),
	.Q(divisor_reg[11]),
	.D(n330),
	.CK(clk__L2_N1));
   DFF_X1 divisor_reg_reg_10_ (.QN(n102),
	.Q(divisor_reg[10]),
	.D(n331),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_9_ (.QN(n103),
	.Q(divisor_reg[9]),
	.D(n332),
	.CK(clk__L2_N2));
   DFF_X1 divisor_reg_reg_8_ (.QN(n104),
	.Q(divisor_reg[8]),
	.D(n333),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_38_ (.QN(n30),
	.Q(remainder_reg[38]),
	.D(n273),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_37_ (.QN(n31),
	.Q(remainder_reg[37]),
	.D(n274),
	.CK(clk__L2_N5));
   DFF_X1 remainder_reg_reg_36_ (.QN(n32),
	.Q(remainder_reg[36]),
	.D(n275),
	.CK(clk__L2_N5));
   DFF_X1 remainder_reg_reg_35_ (.QN(n33),
	.Q(remainder_reg[35]),
	.D(n276),
	.CK(clk__L2_N5));
   DFF_X1 remainder_reg_reg_34_ (.QN(n34),
	.Q(remainder_reg[34]),
	.D(n277),
	.CK(clk__L2_N5));
   DFF_X1 remainder_reg_reg_0_ (.QN(n68),
	.Q(remainder_reg[0]),
	.D(n429),
	.CK(clk__L2_N0));
   DFF_X1 cnt_reg_reg_0_ (.QN(n75),
	.Q(cnt_reg[0]),
	.D(n342),
	.CK(clk__L2_N1));
   DFF_X1 remainder_reg_reg_63_ (.QN(n4),
	.Q(remainder_reg[63]),
	.D(n248),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_62_ (.QN(n6),
	.Q(remainder_reg[62]),
	.D(n249),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_61_ (.QN(n7),
	.Q(remainder_reg[61]),
	.D(n250),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_60_ (.QN(n8),
	.Q(remainder_reg[60]),
	.D(n251),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_59_ (.QN(n9),
	.Q(remainder_reg[59]),
	.D(n252),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_48_ (.QN(n20),
	.Q(remainder_reg[48]),
	.D(n263),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_33_ (.QN(n35),
	.Q(remainder_reg[33]),
	.D(n278),
	.CK(clk__L2_N5));
   DFF_X1 remainder_reg_reg_58_ (.QN(n10),
	.Q(remainder_reg[58]),
	.D(n253),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_57_ (.QN(n11),
	.Q(remainder_reg[57]),
	.D(n254),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_56_ (.QN(n12),
	.Q(remainder_reg[56]),
	.D(n255),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_55_ (.QN(n13),
	.Q(remainder_reg[55]),
	.D(n256),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_54_ (.QN(n14),
	.Q(remainder_reg[54]),
	.D(n257),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_53_ (.QN(n15),
	.Q(remainder_reg[53]),
	.D(n258),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_52_ (.QN(n16),
	.Q(remainder_reg[52]),
	.D(n259),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_51_ (.QN(n17),
	.Q(remainder_reg[51]),
	.D(n260),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_50_ (.QN(n18),
	.Q(remainder_reg[50]),
	.D(n261),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_49_ (.QN(n19),
	.Q(remainder_reg[49]),
	.D(n262),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_47_ (.QN(n21),
	.Q(remainder_reg[47]),
	.D(n264),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_46_ (.QN(n22),
	.Q(remainder_reg[46]),
	.D(n265),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_45_ (.QN(n23),
	.Q(remainder_reg[45]),
	.D(n266),
	.CK(clk__L2_N3));
   DFF_X1 remainder_reg_reg_44_ (.QN(n24),
	.Q(remainder_reg[44]),
	.D(n267),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_43_ (.QN(n25),
	.Q(remainder_reg[43]),
	.D(n268),
	.CK(clk__L2_N2));
   DFF_X1 remainder_reg_reg_42_ (.QN(n26),
	.Q(remainder_reg[42]),
	.D(n269),
	.CK(clk__L2_N4));
   DFF_X1 remainder_reg_reg_41_ (.QN(n27),
	.Q(remainder_reg[41]),
	.D(n270),
	.CK(clk__L2_N4));
   AND2_X1 U312 (.ZN(n346),
	.A2(n384),
	.A1(n428));
   AND2_X1 U315 (.ZN(n349),
	.A2(n385),
	.A1(n387));
   AND2_X1 U318 (.ZN(n350),
	.A2(n178),
	.A1(remainder_reg[0]));
   AND2_X1 U319 (.ZN(n351),
	.A2(n347),
	.A1(dividend[0]));
   AND2_X2 U335 (.ZN(n353),
	.A2(n345),
	.A1(alu_result[32]));
   NOR4_X1 U346 (.ZN(n236),
	.A4(n245),
	.A3(n244),
	.A2(n243),
	.A1(n242));
   NOR4_X1 U347 (.ZN(n237),
	.A4(n241),
	.A3(n240),
	.A2(n239),
	.A1(n238));
   NAND2_X1 U353 (.ZN(n180),
	.A2(n347),
	.A1(dividend[31]));
   OAI221_X1 U354 (.ZN(n280),
	.C2(n38),
	.C1(n430),
	.B2(n470),
	.B1(n39),
	.A(n182));
   NAND2_X1 U355 (.ZN(n182),
	.A2(n347),
	.A1(dividend[30]));
   OAI221_X1 U356 (.ZN(n281),
	.C2(n39),
	.C1(n430),
	.B2(n470),
	.B1(n40),
	.A(n183));
   NAND2_X1 U357 (.ZN(n183),
	.A2(n347),
	.A1(dividend[29]));
   OAI221_X1 U358 (.ZN(n282),
	.C2(n40),
	.C1(n430),
	.B2(n470),
	.B1(n41),
	.A(n184));
   NAND2_X1 U359 (.ZN(n184),
	.A2(n347),
	.A1(dividend[28]));
   OAI221_X1 U360 (.ZN(n283),
	.C2(n41),
	.C1(n430),
	.B2(n470),
	.B1(n42),
	.A(n185));
   NAND2_X1 U361 (.ZN(n185),
	.A2(n347),
	.A1(dividend[27]));
   OAI221_X1 U362 (.ZN(n284),
	.C2(n42),
	.C1(n430),
	.B2(n470),
	.B1(n43),
	.A(n186));
   NAND2_X1 U363 (.ZN(n186),
	.A2(n347),
	.A1(dividend[26]));
   OAI221_X1 U364 (.ZN(n285),
	.C2(n43),
	.C1(n430),
	.B2(n470),
	.B1(n44),
	.A(n187));
   NAND2_X1 U365 (.ZN(n187),
	.A2(n347),
	.A1(dividend[25]));
   OAI221_X1 U366 (.ZN(n286),
	.C2(n44),
	.C1(n430),
	.B2(n470),
	.B1(n45),
	.A(n188));
   NAND2_X1 U367 (.ZN(n188),
	.A2(n347),
	.A1(dividend[24]));
   OAI221_X1 U368 (.ZN(n287),
	.C2(n45),
	.C1(n430),
	.B2(n470),
	.B1(n46),
	.A(n189));
   NAND2_X1 U369 (.ZN(n189),
	.A2(n347),
	.A1(dividend[23]));
   OAI221_X1 U370 (.ZN(n288),
	.C2(n46),
	.C1(n430),
	.B2(n470),
	.B1(n47),
	.A(n190));
   NAND2_X1 U371 (.ZN(n190),
	.A2(n347),
	.A1(dividend[22]));
   OAI221_X1 U372 (.ZN(n289),
	.C2(n47),
	.C1(n430),
	.B2(n470),
	.B1(n48),
	.A(n191));
   NAND2_X1 U373 (.ZN(n191),
	.A2(n347),
	.A1(dividend[21]));
   OAI221_X1 U374 (.ZN(n290),
	.C2(n48),
	.C1(n430),
	.B2(n470),
	.B1(n49),
	.A(n192));
   NAND2_X1 U375 (.ZN(n192),
	.A2(n347),
	.A1(dividend[20]));
   OAI221_X1 U376 (.ZN(n291),
	.C2(n49),
	.C1(n430),
	.B2(n470),
	.B1(n50),
	.A(n193));
   NAND2_X1 U377 (.ZN(n193),
	.A2(n347),
	.A1(dividend[19]));
   OAI221_X1 U378 (.ZN(n292),
	.C2(n50),
	.C1(n430),
	.B2(n470),
	.B1(n51),
	.A(n194));
   NAND2_X1 U379 (.ZN(n194),
	.A2(n347),
	.A1(dividend[18]));
   OAI221_X1 U380 (.ZN(n293),
	.C2(n51),
	.C1(n430),
	.B2(n470),
	.B1(n52),
	.A(n195));
   NAND2_X1 U381 (.ZN(n195),
	.A2(n347),
	.A1(dividend[17]));
   OAI221_X1 U382 (.ZN(n294),
	.C2(n52),
	.C1(n430),
	.B2(n470),
	.B1(n53),
	.A(n196));
   NAND2_X1 U383 (.ZN(n196),
	.A2(n347),
	.A1(dividend[16]));
   OAI221_X1 U384 (.ZN(n295),
	.C2(n53),
	.C1(n430),
	.B2(n470),
	.B1(n54),
	.A(n197));
   NAND2_X1 U385 (.ZN(n197),
	.A2(n347),
	.A1(dividend[15]));
   OAI221_X1 U386 (.ZN(n296),
	.C2(n54),
	.C1(n430),
	.B2(n470),
	.B1(n55),
	.A(n198));
   NAND2_X1 U387 (.ZN(n198),
	.A2(n347),
	.A1(dividend[14]));
   OAI221_X1 U388 (.ZN(n297),
	.C2(n55),
	.C1(n430),
	.B2(n470),
	.B1(n56),
	.A(n199));
   NAND2_X1 U389 (.ZN(n199),
	.A2(n347),
	.A1(dividend[13]));
   OAI221_X1 U390 (.ZN(n298),
	.C2(n56),
	.C1(n430),
	.B2(n470),
	.B1(n57),
	.A(n200));
   NAND2_X1 U391 (.ZN(n200),
	.A2(n347),
	.A1(dividend[12]));
   OAI221_X1 U392 (.ZN(n299),
	.C2(n57),
	.C1(n430),
	.B2(n470),
	.B1(n58),
	.A(n201));
   NAND2_X1 U393 (.ZN(n201),
	.A2(n347),
	.A1(dividend[11]));
   OAI221_X1 U394 (.ZN(n300),
	.C2(n58),
	.C1(n430),
	.B2(n470),
	.B1(n59),
	.A(n202));
   NAND2_X1 U395 (.ZN(n202),
	.A2(n347),
	.A1(dividend[10]));
   OAI221_X1 U396 (.ZN(n301),
	.C2(n59),
	.C1(n430),
	.B2(n470),
	.B1(n60),
	.A(n203));
   NAND2_X1 U397 (.ZN(n203),
	.A2(n347),
	.A1(dividend[9]));
   OAI221_X1 U398 (.ZN(n302),
	.C2(n60),
	.C1(n430),
	.B2(n470),
	.B1(n61),
	.A(n204));
   NAND2_X1 U399 (.ZN(n204),
	.A2(n347),
	.A1(dividend[8]));
   OAI221_X1 U400 (.ZN(n303),
	.C2(n61),
	.C1(n430),
	.B2(n470),
	.B1(n62),
	.A(n205));
   NAND2_X1 U401 (.ZN(n205),
	.A2(n347),
	.A1(dividend[7]));
   OAI221_X1 U402 (.ZN(n304),
	.C2(n62),
	.C1(n430),
	.B2(n470),
	.B1(n63),
	.A(n206));
   NAND2_X1 U403 (.ZN(n206),
	.A2(n347),
	.A1(dividend[6]));
   OAI221_X1 U404 (.ZN(n305),
	.C2(n63),
	.C1(n430),
	.B2(n470),
	.B1(n64),
	.A(n207));
   NAND2_X1 U405 (.ZN(n207),
	.A2(n347),
	.A1(dividend[5]));
   OAI221_X1 U406 (.ZN(n306),
	.C2(n64),
	.C1(n430),
	.B2(n470),
	.B1(n65),
	.A(n208));
   NAND2_X1 U407 (.ZN(n208),
	.A2(n347),
	.A1(dividend[4]));
   OAI221_X1 U408 (.ZN(n307),
	.C2(n65),
	.C1(n430),
	.B2(n470),
	.B1(n66),
	.A(n209));
   NAND2_X1 U409 (.ZN(n209),
	.A2(n347),
	.A1(dividend[3]));
   OAI221_X1 U410 (.ZN(n308),
	.C2(n66),
	.C1(n430),
	.B2(n470),
	.B1(n67),
	.A(n210));
   NAND2_X1 U411 (.ZN(n210),
	.A2(n347),
	.A1(dividend[2]));
   INV_X1 U412 (.ZN(n435),
	.A(n221));
   AOI22_X1 U413 (.ZN(n221),
	.B2(N234),
	.B1(n345),
	.A2(cnt_reg[5]),
	.A1(n178));
   INV_X1 U414 (.ZN(n434),
	.A(n222));
   AOI22_X1 U415 (.ZN(n222),
	.B2(N233),
	.B1(n345),
	.A2(cnt_reg[4]),
	.A1(n178));
   INV_X1 U416 (.ZN(n433),
	.A(n223));
   AOI22_X1 U417 (.ZN(n223),
	.B2(N232),
	.B1(n345),
	.A2(cnt_reg[3]),
	.A1(n178));
   INV_X1 U418 (.ZN(n432),
	.A(n224));
   AOI22_X1 U419 (.ZN(n224),
	.B2(N231),
	.B1(n345),
	.A2(cnt_reg[2]),
	.A1(n178));
   INV_X1 U420 (.ZN(n431),
	.A(n225));
   AOI22_X1 U421 (.ZN(n225),
	.B2(N230),
	.B1(n345),
	.A2(cnt_reg[1]),
	.A1(n178));
   OAI22_X1 U422 (.ZN(n342),
	.B2(cnt_reg[0]),
	.B1(n470),
	.A2(n75),
	.A1(n430));
   OAI21_X1 U423 (.ZN(n344),
	.B2(n227),
	.B1(n437),
	.A(n228));
   INV_X1 U424 (.ZN(n437),
	.A(start));
   NOR4_X1 U425 (.ZN(n229),
	.A4(cnt_reg[1]),
	.A3(cnt_reg[2]),
	.A2(cnt_reg[3]),
	.A1(cnt_reg[4]));
   NAND2_X1 U426 (.ZN(n343),
	.A2(n470),
	.A1(n226));
   NOR2_X1 U428 (.ZN(quotient[2]),
	.A2(n66),
	.A1(FE_OFN0_n147));
   NOR2_X1 U429 (.ZN(quotient[3]),
	.A2(n65),
	.A1(FE_OFN0_n147));
   NOR2_X1 U430 (.ZN(quotient[4]),
	.A2(n64),
	.A1(FE_OFN0_n147));
   NOR2_X1 U431 (.ZN(quotient[5]),
	.A2(n63),
	.A1(FE_OFN0_n147));
   NOR2_X1 U432 (.ZN(quotient[6]),
	.A2(n62),
	.A1(FE_OFN0_n147));
   NOR2_X1 U433 (.ZN(quotient[7]),
	.A2(n61),
	.A1(FE_OFN0_n147));
   NOR2_X1 U434 (.ZN(quotient[8]),
	.A2(n60),
	.A1(FE_OFN0_n147));
   NOR2_X1 U435 (.ZN(quotient[9]),
	.A2(n59),
	.A1(FE_OFN0_n147));
   NOR2_X1 U436 (.ZN(quotient[10]),
	.A2(n58),
	.A1(FE_OFN0_n147));
   NOR2_X1 U437 (.ZN(quotient[11]),
	.A2(n57),
	.A1(FE_OFN0_n147));
   NOR2_X1 U438 (.ZN(quotient[12]),
	.A2(n56),
	.A1(FE_OFN0_n147));
   NOR2_X1 U439 (.ZN(quotient[13]),
	.A2(n55),
	.A1(FE_OFN0_n147));
   NOR2_X1 U440 (.ZN(quotient[14]),
	.A2(n54),
	.A1(FE_OFN0_n147));
   NOR2_X1 U441 (.ZN(quotient[15]),
	.A2(n53),
	.A1(FE_OFN0_n147));
   NOR2_X1 U442 (.ZN(quotient[16]),
	.A2(n52),
	.A1(FE_OFN0_n147));
   NOR2_X1 U443 (.ZN(quotient[17]),
	.A2(n51),
	.A1(FE_OFN0_n147));
   NOR2_X1 U444 (.ZN(quotient[18]),
	.A2(n50),
	.A1(FE_OFN0_n147));
   NOR2_X1 U445 (.ZN(quotient[19]),
	.A2(n49),
	.A1(FE_OFN0_n147));
   NOR2_X1 U446 (.ZN(quotient[20]),
	.A2(n48),
	.A1(FE_OFN0_n147));
   NOR2_X1 U447 (.ZN(quotient[21]),
	.A2(n47),
	.A1(FE_OFN0_n147));
   NOR2_X1 U448 (.ZN(quotient[22]),
	.A2(n46),
	.A1(FE_OFN0_n147));
   NOR2_X1 U449 (.ZN(quotient[23]),
	.A2(n45),
	.A1(FE_OFN0_n147));
   NOR2_X1 U450 (.ZN(quotient[24]),
	.A2(n44),
	.A1(FE_OFN0_n147));
   NOR2_X1 U451 (.ZN(quotient[25]),
	.A2(n43),
	.A1(FE_OFN0_n147));
   NOR2_X1 U452 (.ZN(quotient[26]),
	.A2(n42),
	.A1(FE_OFN0_n147));
   NOR2_X1 U453 (.ZN(quotient[27]),
	.A2(n41),
	.A1(FE_OFN0_n147));
   NOR2_X1 U454 (.ZN(quotient[28]),
	.A2(n40),
	.A1(FE_OFN0_n147));
   NOR2_X1 U455 (.ZN(quotient[29]),
	.A2(n39),
	.A1(FE_OFN0_n147));
   NOR2_X1 U456 (.ZN(quotient[30]),
	.A2(n38),
	.A1(FE_OFN0_n147));
   NOR2_X1 U457 (.ZN(quotient[1]),
	.A2(n67),
	.A1(FE_OFN0_n147));
   NAND2_X1 U459 (.ZN(n218),
	.A2(n220),
	.A1(n428));
   INV_X1 U461 (.ZN(n449),
	.A(divisor[20]));
   INV_X1 U462 (.ZN(n448),
	.A(divisor[21]));
   INV_X1 U463 (.ZN(n447),
	.A(divisor[22]));
   INV_X1 U464 (.ZN(n446),
	.A(divisor[23]));
   INV_X1 U465 (.ZN(n452),
	.A(divisor[17]));
   INV_X1 U466 (.ZN(n451),
	.A(divisor[18]));
   INV_X1 U467 (.ZN(n450),
	.A(divisor[19]));
   INV_X1 U468 (.ZN(n468),
	.A(divisor[1]));
   INV_X1 U469 (.ZN(n456),
	.A(divisor[13]));
   INV_X1 U470 (.ZN(n455),
	.A(divisor[14]));
   INV_X1 U471 (.ZN(n454),
	.A(divisor[15]));
   INV_X1 U472 (.ZN(n453),
	.A(divisor[16]));
   INV_X1 U473 (.ZN(n469),
	.A(divisor[0]));
   INV_X1 U474 (.ZN(n459),
	.A(divisor[10]));
   INV_X1 U475 (.ZN(n458),
	.A(divisor[11]));
   INV_X1 U476 (.ZN(n457),
	.A(divisor[12]));
   INV_X1 U477 (.ZN(n463),
	.A(divisor[6]));
   INV_X1 U478 (.ZN(n462),
	.A(divisor[7]));
   INV_X1 U479 (.ZN(n461),
	.A(divisor[8]));
   INV_X1 U480 (.ZN(n460),
	.A(divisor[9]));
   INV_X1 U481 (.ZN(n438),
	.A(divisor[31]));
   INV_X1 U482 (.ZN(n466),
	.A(divisor[3]));
   INV_X1 U483 (.ZN(n465),
	.A(divisor[4]));
   INV_X1 U484 (.ZN(n464),
	.A(divisor[5]));
   INV_X1 U485 (.ZN(n441),
	.A(divisor[28]));
   INV_X1 U486 (.ZN(n440),
	.A(divisor[29]));
   INV_X1 U487 (.ZN(n467),
	.A(divisor[2]));
   INV_X1 U488 (.ZN(n439),
	.A(divisor[30]));
   INV_X1 U489 (.ZN(n445),
	.A(divisor[24]));
   INV_X1 U490 (.ZN(n444),
	.A(divisor[25]));
   INV_X1 U491 (.ZN(n443),
	.A(divisor[26]));
   INV_X1 U492 (.ZN(n442),
	.A(divisor[27]));
   INV_X1 U493 (.ZN(n428),
	.A(rst));
   NAND2_X1 U497 (.ZN(n227),
	.A2(n386),
	.A1(n349));
   AOI21_X1 U498 (.ZN(n388),
	.B2(n387),
	.B1(state_reg_1_),
	.A(start));
   OAI21_X1 U499 (.ZN(n389),
	.B2(done),
	.B1(n388),
	.A(n428));
   OAI221_X1 U502 (.ZN(n279),
	.C2(n470),
	.C1(n38),
	.B2(n430),
	.B1(n37),
	.A(n180));
   AOI22_X1 U503 (.ZN(n390),
	.B2(n178),
	.B1(remainder_reg[32]),
	.A2(n345),
	.A1(remainder_reg[31]));
   INV_X1 U504 (.ZN(n436),
	.A(n390));
   AOI22_X1 U506 (.ZN(n392),
	.B2(n353),
	.B1(remainder_reg[32]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[0]));
   OAI21_X1 U507 (.ZN(n278),
	.B2(n430),
	.B1(n35),
	.A(n392));
   AOI22_X1 U508 (.ZN(n393),
	.B2(n353),
	.B1(remainder_reg[33]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[1]));
   OAI21_X1 U509 (.ZN(n277),
	.B2(n430),
	.B1(n34),
	.A(n393));
   AOI22_X1 U510 (.ZN(n394),
	.B2(n353),
	.B1(remainder_reg[34]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[2]));
   OAI21_X1 U511 (.ZN(n276),
	.B2(n430),
	.B1(n33),
	.A(n394));
   AOI22_X1 U512 (.ZN(n395),
	.B2(n353),
	.B1(remainder_reg[35]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[3]));
   OAI21_X1 U513 (.ZN(n275),
	.B2(n430),
	.B1(n32),
	.A(n395));
   AOI22_X1 U514 (.ZN(n396),
	.B2(n353),
	.B1(remainder_reg[36]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[4]));
   OAI21_X1 U515 (.ZN(n274),
	.B2(n430),
	.B1(n31),
	.A(n396));
   AOI22_X1 U516 (.ZN(n397),
	.B2(n353),
	.B1(remainder_reg[37]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[5]));
   OAI21_X1 U517 (.ZN(n273),
	.B2(n430),
	.B1(n30),
	.A(n397));
   AOI22_X1 U518 (.ZN(n398),
	.B2(n353),
	.B1(remainder_reg[38]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[6]));
   OAI21_X1 U519 (.ZN(n272),
	.B2(n430),
	.B1(n29),
	.A(n398));
   AOI22_X1 U520 (.ZN(n399),
	.B2(n353),
	.B1(remainder_reg[39]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[7]));
   OAI21_X1 U521 (.ZN(n271),
	.B2(n430),
	.B1(n28),
	.A(n399));
   AOI22_X1 U522 (.ZN(n400),
	.B2(n353),
	.B1(remainder_reg[40]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[8]));
   OAI21_X1 U523 (.ZN(n270),
	.B2(n430),
	.B1(n27),
	.A(n400));
   AOI22_X1 U524 (.ZN(n401),
	.B2(n353),
	.B1(remainder_reg[41]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[9]));
   OAI21_X1 U525 (.ZN(n269),
	.B2(n430),
	.B1(n26),
	.A(n401));
   AOI22_X1 U526 (.ZN(n402),
	.B2(n353),
	.B1(remainder_reg[42]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[10]));
   OAI21_X1 U527 (.ZN(n268),
	.B2(n430),
	.B1(n25),
	.A(n402));
   AOI22_X1 U528 (.ZN(n403),
	.B2(n353),
	.B1(remainder_reg[43]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[11]));
   OAI21_X1 U529 (.ZN(n267),
	.B2(n430),
	.B1(n24),
	.A(n403));
   AOI22_X1 U530 (.ZN(n404),
	.B2(n353),
	.B1(remainder_reg[44]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[12]));
   OAI21_X1 U531 (.ZN(n266),
	.B2(n430),
	.B1(n23),
	.A(n404));
   AOI22_X1 U532 (.ZN(n405),
	.B2(n353),
	.B1(remainder_reg[45]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[13]));
   OAI21_X1 U533 (.ZN(n265),
	.B2(n430),
	.B1(n22),
	.A(n405));
   AOI22_X1 U534 (.ZN(n406),
	.B2(n353),
	.B1(remainder_reg[46]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[14]));
   OAI21_X1 U535 (.ZN(n264),
	.B2(n430),
	.B1(n21),
	.A(n406));
   AOI22_X1 U536 (.ZN(n407),
	.B2(n353),
	.B1(remainder_reg[47]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[15]));
   OAI21_X1 U537 (.ZN(n263),
	.B2(n430),
	.B1(n20),
	.A(n407));
   AOI22_X1 U538 (.ZN(n408),
	.B2(n353),
	.B1(remainder_reg[48]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[16]));
   OAI21_X1 U539 (.ZN(n262),
	.B2(n430),
	.B1(n19),
	.A(n408));
   AOI22_X1 U540 (.ZN(n409),
	.B2(n353),
	.B1(remainder_reg[49]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[17]));
   OAI21_X1 U541 (.ZN(n261),
	.B2(n430),
	.B1(n18),
	.A(n409));
   AOI22_X1 U542 (.ZN(n410),
	.B2(n353),
	.B1(remainder_reg[50]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[18]));
   OAI21_X1 U543 (.ZN(n260),
	.B2(n430),
	.B1(n17),
	.A(n410));
   AOI22_X1 U544 (.ZN(n411),
	.B2(n353),
	.B1(remainder_reg[51]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[19]));
   OAI21_X1 U545 (.ZN(n259),
	.B2(n430),
	.B1(n16),
	.A(n411));
   AOI22_X1 U546 (.ZN(n412),
	.B2(n353),
	.B1(remainder_reg[52]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[20]));
   OAI21_X1 U547 (.ZN(n258),
	.B2(n430),
	.B1(n15),
	.A(n412));
   AOI22_X1 U548 (.ZN(n413),
	.B2(n353),
	.B1(remainder_reg[53]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[21]));
   OAI21_X1 U549 (.ZN(n257),
	.B2(n430),
	.B1(n14),
	.A(n413));
   AOI22_X1 U550 (.ZN(n414),
	.B2(n353),
	.B1(remainder_reg[54]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[22]));
   OAI21_X1 U551 (.ZN(n256),
	.B2(n430),
	.B1(n13),
	.A(n414));
   AOI22_X1 U552 (.ZN(n415),
	.B2(n353),
	.B1(remainder_reg[55]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[23]));
   OAI21_X1 U553 (.ZN(n255),
	.B2(n430),
	.B1(n12),
	.A(n415));
   AOI22_X1 U554 (.ZN(n416),
	.B2(n353),
	.B1(remainder_reg[56]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[24]));
   OAI21_X1 U555 (.ZN(n254),
	.B2(n430),
	.B1(n11),
	.A(n416));
   AOI22_X1 U556 (.ZN(n417),
	.B2(n353),
	.B1(remainder_reg[57]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[25]));
   OAI21_X1 U557 (.ZN(n253),
	.B2(n430),
	.B1(n10),
	.A(n417));
   AOI22_X1 U558 (.ZN(n418),
	.B2(n353),
	.B1(remainder_reg[58]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[26]));
   OAI21_X1 U559 (.ZN(n252),
	.B2(n430),
	.B1(n9),
	.A(n418));
   AOI22_X1 U560 (.ZN(n419),
	.B2(n353),
	.B1(remainder_reg[59]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[27]));
   OAI21_X1 U561 (.ZN(n251),
	.B2(n430),
	.B1(n8),
	.A(n419));
   AOI22_X1 U562 (.ZN(n420),
	.B2(n353),
	.B1(remainder_reg[60]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[28]));
   OAI21_X1 U563 (.ZN(n250),
	.B2(n430),
	.B1(n7),
	.A(n420));
   AOI22_X1 U564 (.ZN(n421),
	.B2(n353),
	.B1(remainder_reg[61]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[29]));
   OAI21_X1 U565 (.ZN(n249),
	.B2(n430),
	.B1(n6),
	.A(n421));
   AOI22_X1 U566 (.ZN(n422),
	.B2(n353),
	.B1(remainder_reg[62]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[30]));
   OAI21_X1 U567 (.ZN(n248),
	.B2(n430),
	.B1(n4),
	.A(n422));
   OAI22_X1 U569 (.ZN(n310),
	.B2(n348),
	.B1(n81),
	.A2(n424),
	.A1(n438));
   OAI22_X1 U570 (.ZN(n311),
	.B2(n348),
	.B1(n82),
	.A2(n424),
	.A1(n439));
   OAI22_X1 U571 (.ZN(n312),
	.B2(n348),
	.B1(n83),
	.A2(n424),
	.A1(n440));
   OAI22_X1 U572 (.ZN(n313),
	.B2(n348),
	.B1(n84),
	.A2(n424),
	.A1(n441));
   OAI22_X1 U573 (.ZN(n314),
	.B2(n348),
	.B1(n85),
	.A2(n424),
	.A1(n442));
   OAI22_X1 U574 (.ZN(n315),
	.B2(n348),
	.B1(n86),
	.A2(n424),
	.A1(n443));
   OAI22_X1 U575 (.ZN(n316),
	.B2(n348),
	.B1(n87),
	.A2(n424),
	.A1(n444));
   OAI22_X1 U576 (.ZN(n317),
	.B2(n348),
	.B1(n88),
	.A2(n424),
	.A1(n445));
   OAI22_X1 U577 (.ZN(n318),
	.B2(n348),
	.B1(n89),
	.A2(n424),
	.A1(n446));
   OAI22_X1 U578 (.ZN(n319),
	.B2(n348),
	.B1(n90),
	.A2(n424),
	.A1(n447));
   OAI22_X1 U579 (.ZN(n320),
	.B2(n348),
	.B1(n91),
	.A2(n424),
	.A1(n448));
   OAI22_X1 U580 (.ZN(n321),
	.B2(n348),
	.B1(n92),
	.A2(n424),
	.A1(n449));
   OAI22_X1 U581 (.ZN(n322),
	.B2(n348),
	.B1(n93),
	.A2(n424),
	.A1(n450));
   OAI22_X1 U582 (.ZN(n323),
	.B2(n348),
	.B1(n94),
	.A2(n424),
	.A1(n451));
   OAI22_X1 U583 (.ZN(n324),
	.B2(n348),
	.B1(n95),
	.A2(n424),
	.A1(n452));
   OAI22_X1 U584 (.ZN(n325),
	.B2(n348),
	.B1(n96),
	.A2(n424),
	.A1(n453));
   OAI22_X1 U585 (.ZN(n326),
	.B2(n348),
	.B1(n97),
	.A2(n424),
	.A1(n454));
   OAI22_X1 U586 (.ZN(n327),
	.B2(n348),
	.B1(n98),
	.A2(n424),
	.A1(n455));
   OAI22_X1 U587 (.ZN(n328),
	.B2(n348),
	.B1(n99),
	.A2(n424),
	.A1(n456));
   OAI22_X1 U588 (.ZN(n329),
	.B2(n348),
	.B1(n100),
	.A2(n424),
	.A1(n457));
   OAI22_X1 U589 (.ZN(n330),
	.B2(n348),
	.B1(n101),
	.A2(n424),
	.A1(n458));
   OAI22_X1 U590 (.ZN(n331),
	.B2(n348),
	.B1(n102),
	.A2(n424),
	.A1(n459));
   OAI22_X1 U591 (.ZN(n332),
	.B2(n348),
	.B1(n103),
	.A2(n424),
	.A1(n460));
   OAI22_X1 U592 (.ZN(n333),
	.B2(n348),
	.B1(n104),
	.A2(n424),
	.A1(n461));
   OAI22_X1 U593 (.ZN(n334),
	.B2(n348),
	.B1(n105),
	.A2(n424),
	.A1(n462));
   OAI22_X1 U594 (.ZN(n335),
	.B2(n348),
	.B1(n106),
	.A2(n424),
	.A1(n463));
   OAI22_X1 U595 (.ZN(n336),
	.B2(n348),
	.B1(n107),
	.A2(n424),
	.A1(n464));
   OAI22_X1 U596 (.ZN(n337),
	.B2(n348),
	.B1(n108),
	.A2(n424),
	.A1(n465));
   OAI22_X1 U597 (.ZN(n338),
	.B2(n348),
	.B1(n109),
	.A2(n424),
	.A1(n466));
   OAI22_X1 U598 (.ZN(n339),
	.B2(n348),
	.B1(n110),
	.A2(n424),
	.A1(n467));
   OAI22_X1 U599 (.ZN(n340),
	.B2(n348),
	.B1(n111),
	.A2(n424),
	.A1(n468));
   OAI22_X1 U600 (.ZN(n341),
	.B2(n348),
	.B1(n112),
	.A2(n424),
	.A1(n469));
   NAND2_X1 U602 (.ZN(n426),
	.A2(n347),
	.A1(dividend[1]));
   OAI221_X1 U603 (.ZN(n309),
	.C2(n470),
	.C1(n68),
	.B2(n430),
	.B1(n67),
	.A(n426));
   NOR2_X1 U604 (.ZN(remainder[0]),
	.A2(n35),
	.A1(FE_OFN0_n147));
   NOR2_X1 U605 (.ZN(remainder[1]),
	.A2(n34),
	.A1(FE_OFN0_n147));
   NOR2_X1 U606 (.ZN(remainder[2]),
	.A2(n33),
	.A1(FE_OFN0_n147));
   NOR2_X1 U607 (.ZN(remainder[3]),
	.A2(n32),
	.A1(FE_OFN0_n147));
   NOR2_X1 U608 (.ZN(remainder[4]),
	.A2(n31),
	.A1(FE_OFN0_n147));
   NOR2_X1 U609 (.ZN(remainder[5]),
	.A2(n30),
	.A1(FE_OFN0_n147));
   NOR2_X1 U610 (.ZN(remainder[6]),
	.A2(n29),
	.A1(FE_OFN0_n147));
   NOR2_X1 U611 (.ZN(remainder[7]),
	.A2(n28),
	.A1(FE_OFN0_n147));
   NOR2_X1 U612 (.ZN(remainder[8]),
	.A2(n27),
	.A1(FE_OFN0_n147));
   NOR2_X1 U613 (.ZN(remainder[9]),
	.A2(n26),
	.A1(FE_OFN0_n147));
   NOR2_X1 U614 (.ZN(remainder[10]),
	.A2(n25),
	.A1(FE_OFN0_n147));
   NOR2_X1 U615 (.ZN(remainder[11]),
	.A2(n24),
	.A1(FE_OFN0_n147));
   NOR2_X1 U616 (.ZN(remainder[12]),
	.A2(n23),
	.A1(FE_OFN0_n147));
   NOR2_X1 U617 (.ZN(remainder[13]),
	.A2(n22),
	.A1(FE_OFN0_n147));
   NOR2_X1 U618 (.ZN(remainder[14]),
	.A2(n21),
	.A1(FE_OFN0_n147));
   NOR2_X1 U619 (.ZN(remainder[15]),
	.A2(n20),
	.A1(FE_OFN0_n147));
   NOR2_X1 U620 (.ZN(remainder[16]),
	.A2(n19),
	.A1(FE_OFN0_n147));
   NOR2_X1 U621 (.ZN(remainder[17]),
	.A2(n18),
	.A1(FE_OFN0_n147));
   NOR2_X1 U622 (.ZN(remainder[18]),
	.A2(n17),
	.A1(FE_OFN0_n147));
   NOR2_X1 U623 (.ZN(remainder[19]),
	.A2(n16),
	.A1(FE_OFN0_n147));
   NOR2_X1 U624 (.ZN(remainder[20]),
	.A2(n15),
	.A1(FE_OFN0_n147));
   NOR2_X1 U625 (.ZN(remainder[21]),
	.A2(n14),
	.A1(FE_OFN0_n147));
   NOR2_X1 U626 (.ZN(remainder[22]),
	.A2(n13),
	.A1(FE_OFN0_n147));
   NOR2_X1 U627 (.ZN(remainder[23]),
	.A2(n12),
	.A1(FE_OFN0_n147));
   NOR2_X1 U628 (.ZN(remainder[24]),
	.A2(n11),
	.A1(FE_OFN0_n147));
   NOR2_X1 U629 (.ZN(remainder[25]),
	.A2(n10),
	.A1(FE_OFN0_n147));
   NOR2_X1 U630 (.ZN(remainder[26]),
	.A2(n9),
	.A1(FE_OFN0_n147));
   NOR2_X1 U631 (.ZN(remainder[27]),
	.A2(n8),
	.A1(FE_OFN0_n147));
   NOR2_X1 U632 (.ZN(remainder[28]),
	.A2(n7),
	.A1(FE_OFN0_n147));
   NOR2_X1 U633 (.ZN(remainder[29]),
	.A2(n6),
	.A1(FE_OFN0_n147));
   NOR2_X1 U634 (.ZN(remainder[30]),
	.A2(n4),
	.A1(FE_OFN0_n147));
   AOI22_X1 U635 (.ZN(n427),
	.B2(n353),
	.B1(remainder_reg[63]),
	.A2(FE_OFN1_n352),
	.A1(alu_result[31]));
   OAI21_X1 U636 (.ZN(n247),
	.B2(n430),
	.B1(n3),
	.A(n427));
   NOR2_X1 U637 (.ZN(remainder[31]),
	.A2(FE_OFN0_n147),
	.A1(n3));
   NOR2_X1 U638 (.ZN(quotient[0]),
	.A2(n68),
	.A1(FE_OFN0_n147));
   XOR2_X1 U639 (.Z(N234),
	.B(cnt_reg[5]),
	.A(add_117_carry[5]));
   INV_X4 U311 (.ZN(n430),
	.A(n178));
   NAND2_X1 U313 (.ZN(n178),
	.A2(n227),
	.A1(n389));
   AND2_X2 U314 (.ZN(n348),
	.A2(n218),
	.A1(n423));
   NAND2_X2 U316 (.ZN(n424),
	.A2(n346),
	.A1(n218));
   NAND2_X1 U317 (.ZN(n147),
	.A2(state_reg_1_),
	.A1(done));
   AND3_X2 U320 (.ZN(n347),
	.A3(n349),
	.A2(n389),
	.A1(n346));
   INV_X1 U322 (.ZN(n423),
	.A(n386));
   NOR2_X1 U323 (.ZN(n386),
	.A2(n384),
	.A1(rst));
   OR3_X1 U324 (.ZN(n429),
	.A3(n351),
	.A2(n350),
	.A1(FE_OFN1_n352));
   NOR2_X1 U325 (.ZN(quotient[31]),
	.A2(FE_OFN0_n147),
	.A1(n37));
   INV_X1 U331 (.ZN(n345),
	.A(n470));
   NAND3_X2 U332 (.ZN(n470),
	.A3(n387),
	.A2(state_reg_1_),
	.A1(n428));
   NOR2_X1 U333 (.ZN(n352),
	.A2(n470),
	.A1(alu_result[32]));
   NAND2_X1 U336 (.ZN(n384),
	.A2(n236),
	.A1(n237));
endmodule

